language: generic
sudo: required
services:
  - docker

before_install:
  - docker build -t cpe111/docker-react -f Dockerfile.dev .

script:
  - docker run -e CI=true cpe111/docker-react npm run test


